// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/agent': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/agent.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/agent.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/agent.put').default>>>>
    }
    '/api/agent/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/agent/detail.get').default>>>>
    }
    '/api/agent/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/agent/list.get').default>>>>
    }
    '/api/chat/group': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/group.post').default>>>>
    }
    '/api/chat/group/exit': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/group/exit.delete').default>>>>
    }
    '/api/chat/group/member': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/group/member.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/group/member.post').default>>>>
    }
    '/api/chat/group/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/group/members.get').default>>>>
    }
    '/api/chat/msg': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/msg.post').default>>>>
    }
    '/api/chat/msg/page': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/msg/page.get').default>>>>
    }
    '/api/chat/msg/read': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/msg/read.put').default>>>>
    }
    '/api/chat/msg/recall': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/msg/recall.put').default>>>>
    }
    '/api/chat/msg/recv': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/msg/recv.get').default>>>>
    }
    '/api/chat/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/session.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/session.post').default>>>>
    }
    '/api/chat/session/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/session/detail.get').default>>>>
    }
    '/api/chat/session/page': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/session/page.get').default>>>>
    }
    '/api/plugin': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/plugin.put').default>>>>
    }
    '/api/plugin/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/plugin/detail.get').default>>>>
    }
    '/api/plugin/install': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/plugin/install.post').default>>>>
    }
    '/api/plugin/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/plugin/list.get').default>>>>
    }
    '/api/plugin/toggle': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/plugin/toggle.put').default>>>>
    }
    '/api/plugin/uninstall': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/plugin/uninstall.delete').default>>>>
    }
    '/api/robot': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/robot.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/robot.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/robot.put').default>>>>
    }
    '/api/robot/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/robot/detail.get').default>>>>
    }
    '/api/robot/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/robot/list.get').default>>>>
    }
    '/api/schedule': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/schedule.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/schedule.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/schedule.put').default>>>>
    }
    '/api/schedule/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/schedule/detail.get').default>>>>
    }
    '/api/schedule/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/schedule/list.get').default>>>>
    }
    '/api/user/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/info.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/info.put').default>>>>
    }
    '/api/user/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/login.post').default>>>>
    }
    '/api/user/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/logout.post').default>>>>
    }
    '/api/user/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/register.post').default>>>>
    }
    '/api/user/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/reset-password.post').default>>>>
    }
    '/api/user/send-code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/send-code.post').default>>>>
    }
  }
}
export {}